'use client';

import { useRef, useCallback } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { CaseDetail } from '@/types/onlineHarms';
import { TFGBV_CLUSTERS } from '@/data/tfgbvQuestions';

interface AdminCaseReviewPDFProps {
  caseData: CaseDetail;
  adminUsername: string;
  generatedAt: string;
}

export default function AdminCaseReviewPDF({ caseData, adminUsername, generatedAt }: AdminCaseReviewPDFProps) {
  const reportRef = useRef<HTMLDivElement>(null);

  const getRiskColor = (risk: string) => {
    switch(risk) {
      case 'low': return '#22C55E';
      case 'moderate': return '#F59E0B';
      case 'high': return '#EF4444';
      case 'critical': return '#DC2626';
      default: return '#6B7280';
    }
  };

  const getTfgbvTypeLabel = (type: string) => {
    const labels: Record<string, string> = {
      sextortion: 'Sextortion',
      cyberstalking: 'Cyberstalking',
      'non-consensual_sharing': 'Non-Consensual Image Sharing',
      deepfake: 'Deepfake/AI Content',
      harassment: 'Online Harassment',
      misinformation: 'Misinformation',
      identity_theft: 'Identity Theft',
      other: 'Other'
    };
    return labels[type] || type;
  };

  const getStatusLabel = (status: string) => {
    return status.replace('_', ' ').toUpperCase();
  };

  const downloadPDF = async () => {
    if (!reportRef.current) return;
    
    const element = reportRef.current;
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff'
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
    
    const imgX = (pdfWidth - imgWidth * ratio) / 2;
    let imgY = 10;
    
    const scaledHeight = imgHeight * ratio * (pdfWidth - 20) / (imgWidth * ratio);
    let heightLeft = scaledHeight;
    let position = imgY;
    
    pdf.addImage(imgData, 'PNG', 10, imgY, pdfWidth - 20, scaledHeight);
    heightLeft -= pdfHeight;
    
    while (heightLeft > 0) {
      position = heightLeft - scaledHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 10, position, pdfWidth - 20, scaledHeight);
      heightLeft -= pdfHeight;
    }
    
    const fileName = `CAT_Case_Review_${caseData.caseId.slice(0, 8)}_${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);
  };

  const assessment = caseData.assessmentResult;

  return (
    <div>
      {/* Download Button */}
      <button
        onClick={downloadPDF}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          padding: '12px 24px',
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          color: 'white',
          border: 'none',
          borderRadius: '8px',
          cursor: 'pointer',
          fontSize: '14px',
          fontWeight: 600,
          marginBottom: '20px',
          boxShadow: '0 4px 12px rgba(102, 126, 234, 0.3)'
        }}
      >
        <span>📥</span>
        Download Case Review PDF
      </button>

      {/* Report Content (for PDF generation) */}
      <div ref={reportRef} style={reportStyles.container}>
        {/* Letterhead */}
        <div style={reportStyles.letterhead}>
          <div style={reportStyles.letterheadTop}>
            <div style={reportStyles.catLogo}>CAT</div>
            <div style={reportStyles.letterheadText}>
              <h1 style={reportStyles.orgName}>CENTRE AGAINST TORTURE</h1>
              <p style={reportStyles.orgTagline}>Protecting Human Rights • Kenya</p>
            </div>
          </div>
          <div style={reportStyles.letterheadLine} />
        </div>

        {/* Report Title */}
        <div style={reportStyles.header}>
          <h1 style={reportStyles.title}>CONFIDENTIAL CASE REVIEW</h1>
          <p style={reportStyles.subtitle}>Online Harms / TFGBV Case Management</p>
        </div>

        {/* Generated Info */}
        <div style={reportStyles.metaBox}>
          <div style={reportStyles.metaGrid}>
            <div>
              <p style={reportStyles.metaLabel}>Generated By:</p>
              <p style={reportStyles.metaValue}>{adminUsername}</p>
            </div>
            <div>
              <p style={reportStyles.metaLabel}>Generated At:</p>
              <p style={reportStyles.metaValue}>{new Date(generatedAt).toLocaleString()}</p>
            </div>
            <div>
              <p style={reportStyles.metaLabel}>Confidentiality:</p>
              <p style={reportStyles.metaValue}>ADMIN ONLY</p>
            </div>
          </div>
        </div>

        {/* Section 1: Case Information */}
        <div style={reportStyles.section}>
          <h2 style={reportStyles.sectionTitle}>1. CASE INFORMATION</h2>
          <div style={reportStyles.infoBox}>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Case ID:</span>
              <span style={reportStyles.infoValue}>{caseData.caseId}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Client ID:</span>
              <span style={reportStyles.infoValue}>{caseData.clientId}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Case Type:</span>
              <span style={reportStyles.infoValue}>{getTfgbvTypeLabel(caseData.tfgbvType)}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Risk Level:</span>
              <span style={{...reportStyles.riskBadge, background: getRiskColor(caseData.riskLevel)}}>
                {caseData.riskLevel.toUpperCase()}
              </span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Status:</span>
              <span style={reportStyles.statusValue}>{getStatusLabel(caseData.status)}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Assigned To:</span>
              <span style={reportStyles.infoValue}>{caseData.assignedTo || 'Unassigned'}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Created:</span>
              <span style={reportStyles.infoValue}>{new Date(caseData.createdAt).toLocaleString()}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Last Updated:</span>
              <span style={reportStyles.infoValue}>{new Date(caseData.updatedAt).toLocaleString()}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Consent Given:</span>
              <span style={reportStyles.infoValue}>{caseData.consentGiven ? 'Yes' : 'No'}</span>
            </div>
          </div>
        </div>

        {/* Section 2: Client/Patient Information */}
        <div style={reportStyles.section}>
          <h2 style={reportStyles.sectionTitle}>2. CLIENT INFORMATION</h2>
          <div style={reportStyles.infoBox}>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Full Name:</span>
              <span style={reportStyles.infoValue}>{caseData.clientFullName || 'Not provided'}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Phone:</span>
              <span style={reportStyles.infoValue}>{caseData.clientPhone || 'Not provided'}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Email:</span>
              <span style={reportStyles.infoValue}>{caseData.clientEmail || 'Not provided'}</span>
            </div>
            <div style={reportStyles.infoRow}>
              <span style={reportStyles.infoLabel}>Contact Status:</span>
              <span style={reportStyles.infoValue}>
                {caseData.clientPhone || caseData.clientEmail ? 'Contactable' : 'Anonymous / No contact'}
              </span>
            </div>
          </div>
        </div>

        {/* Section 3: Incident Description */}
        <div style={reportStyles.section}>
          <h2 style={reportStyles.sectionTitle}>3. INCIDENT DESCRIPTION</h2>
          <div style={reportStyles.descriptionBox}>
            <p style={reportStyles.descriptionText}>{caseData.description}</p>
            {caseData.platforms && caseData.platforms.length > 0 && (
              <div style={reportStyles.platforms}>
                <strong>Platforms:</strong> {caseData.platforms.join(', ')}
              </div>
            )}
          </div>
        </div>

        {/* Section 4: Diagnosis / Assessment Results */}
        {assessment && (
          <div style={reportStyles.section}>
            <h2 style={reportStyles.sectionTitle}>4. DIAGNOSIS & IMPACT ASSESSMENT</h2>
            
            {/* Overall Risk */}
            <div style={{...reportStyles.riskBox, borderColor: getRiskColor(assessment.overallRisk)}}>
              <div style={{...reportStyles.riskBadge, background: getRiskColor(assessment.overallRisk)}}>
                OVERALL RISK: {assessment.overallRisk.toUpperCase()}
              </div>
              <p style={reportStyles.riskDescription}>{assessment.summary}</p>
            </div>

            {/* Cluster Analysis */}
            <h3 style={reportStyles.subsectionTitle}>Impact Analysis by Category:</h3>
            <div style={reportStyles.clustersTable}>
              {Object.entries(assessment.clusterLevels).map(([cluster, level]) => (
                <div key={cluster} style={reportStyles.clusterRow}>
                  <div style={reportStyles.clusterName}>
                    {TFGBV_CLUSTERS[cluster as keyof typeof TFGBV_CLUSTERS]?.en || cluster}
                  </div>
                  <div style={reportStyles.clusterBarContainer}>
                    <div style={{...reportStyles.clusterBar, width: `${assessment.rawScores[cluster]}%`, background: getRiskColor(level)}} />
                  </div>
                  <div style={{...reportStyles.clusterLevel, color: getRiskColor(level)}}>
                    {assessment.rawScores[cluster]}% - {level.toUpperCase()}
                  </div>
                </div>
              ))}
            </div>

            {/* Top Cluster */}
            <div style={reportStyles.topClusterBox}>
              <strong>Primary Concern:</strong> {TFGBV_CLUSTERS[assessment.topCluster as keyof typeof TFGBV_CLUSTERS]?.en || assessment.topCluster}
            </div>

            {/* Recommendations */}
            <h3 style={reportStyles.subsectionTitle}>Recommendations:</h3>
            <ol style={reportStyles.recommendationsList}>
              {assessment.recommendations.map((rec, i) => (
                <li key={i} style={reportStyles.recommendationItem}>
                  <span style={reportStyles.recommendationNumber}>{i + 1}</span>
                  <span>{rec}</span>
                </li>
              ))}
            </ol>
          </div>
        )}

        {/* Section 5: Evidence Summary */}
        {caseData.evidence.length > 0 && (
          <div style={reportStyles.section}>
            <h2 style={reportStyles.sectionTitle}>5. EVIDENCE SUMMARY</h2>
            <p style={reportStyles.evidenceCount}>Total Evidence Items: {caseData.evidence.length}</p>
            <div style={reportStyles.evidenceList}>
              {caseData.evidence.map((ev, idx) => (
                <div key={ev.evidenceId} style={reportStyles.evidenceItem}>
                  <div style={reportStyles.evidenceNumber}>#{idx + 1}</div>
                  <div style={reportStyles.evidenceDetails}>
                    <p><strong>Type:</strong> {ev.type}</p>
                    <p><strong>Filename:</strong> {ev.filename || 'N/A'}</p>
                    <p><strong>Uploaded:</strong> {new Date(ev.uploadedAt).toLocaleString()}</p>
                    <p><strong>Tags:</strong> {ev.tags.join(', ') || 'None'}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Section 6: Admin Notes */}
        {caseData.adminNotes.length > 0 && (
          <div style={reportStyles.section}>
            <h2 style={reportStyles.sectionTitle}>6. CASE NOTES</h2>
            <div style={reportStyles.notesList}>
              {caseData.adminNotes.map((note) => (
                <div key={note.noteId} style={reportStyles.noteItem}>
                  <div style={reportStyles.noteHeader}>
                    <strong>{note.adminUsername}</strong>
                    <span style={reportStyles.noteDate}>{new Date(note.createdAt).toLocaleString()}</span>
                  </div>
                  <p style={reportStyles.noteText}>{note.note}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Section 7: Audit Trail */}
        {caseData.auditLogs.length > 0 && (
          <div style={reportStyles.section}>
            <h2 style={reportStyles.sectionTitle}>7. AUDIT TRAIL (Last 50 Actions)</h2>
            <table style={reportStyles.auditTable}>
              <thead>
                <tr>
                  <th style={reportStyles.auditTh}>Timestamp</th>
                  <th style={reportStyles.auditTh}>Action</th>
                  <th style={reportStyles.auditTh}>Admin</th>
                </tr>
              </thead>
              <tbody>
                {caseData.auditLogs.slice(0, 50).map((log) => (
                  <tr key={log.logId}>
                    <td style={reportStyles.auditTd}>{new Date(log.timestamp).toLocaleString()}</td>
                    <td style={reportStyles.auditTd}>{log.action.replace(/_/g, ' ')}</td>
                    <td style={reportStyles.auditTd}>{log.adminUsername || 'System'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Footer */}
        <div style={reportStyles.footer}>
          <p style={reportStyles.footerText}>
            This document is confidential and intended for authorized personnel only. 
            Centre Against Torture Kenya - Online Harms Case Management System.
          </p>
          <p style={reportStyles.footerNote}>
            Case ID: {caseData.caseId} | Generated: {new Date(generatedAt).toISOString()}
          </p>
        </div>
      </div>
    </div>
  );
}

// Styles for the PDF report
const reportStyles: Record<string, React.CSSProperties> = {
  container: {
    background: 'white',
    padding: '40px',
    maxWidth: '800px',
    margin: '0 auto',
    fontFamily: 'Arial, sans-serif',
    color: '#1f2937',
    lineHeight: 1.6,
  },
  letterhead: {
    marginBottom: '20px',
  },
  letterheadTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '12px',
  },
  catLogo: {
    width: '60px',
    height: '60px',
    background: '#1e40af',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: 'bold',
    borderRadius: '8px',
    border: '3px solid #f59e0b',
  },
  letterheadText: {
    flex: 1,
  },
  orgName: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#1e40af',
    margin: '0 0 4px 0',
    letterSpacing: '1px',
  },
  orgTagline: {
    fontSize: '13px',
    color: '#6b7280',
    margin: 0,
    fontStyle: 'italic',
  },
  letterheadLine: {
    height: '4px',
    background: 'linear-gradient(90deg, #1e40af 0%, #f59e0b 50%, #dc2626 100%)',
    borderRadius: '2px',
  },
  header: {
    textAlign: 'center',
    marginBottom: '30px',
    borderBottom: '3px solid #dc2626',
    paddingBottom: '20px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#dc2626',
    margin: '0 0 8px 0',
  },
  subtitle: {
    fontSize: '14px',
    color: '#6b7280',
    margin: 0,
  },
  metaBox: {
    background: '#fef2f2',
    border: '2px solid #dc2626',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '30px',
  },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
  },
  metaLabel: {
    fontSize: '11px',
    color: '#6b7280',
    margin: '0 0 4px 0',
    textTransform: 'uppercase',
  },
  metaValue: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#1f2937',
    margin: 0,
  },
  section: {
    marginBottom: '30px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#374151',
    margin: '0 0 16px 0',
    paddingBottom: '8px',
    borderBottom: '2px solid #e5e7eb',
  },
  subsectionTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#4b5563',
    margin: '20px 0 12px 0',
  },
  infoBox: {
    background: '#f9fafb',
    borderRadius: '8px',
    padding: '20px',
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 0',
    borderBottom: '1px solid #e5e7eb',
  },
  infoLabel: {
    fontSize: '13px',
    color: '#6b7280',
    fontWeight: 500,
  },
  infoValue: {
    fontSize: '13px',
    color: '#1f2937',
    fontWeight: 600,
  },
  statusValue: {
    fontSize: '12px',
    fontWeight: 'bold',
    color: '#1f2937',
    textTransform: 'uppercase',
  },
  riskBadge: {
    display: 'inline-block',
    padding: '4px 12px',
    borderRadius: '4px',
    color: 'white',
    fontSize: '12px',
    fontWeight: 'bold',
  },
  descriptionBox: {
    background: '#f9fafb',
    borderRadius: '8px',
    padding: '20px',
    borderLeft: '4px solid #667eea',
  },
  descriptionText: {
    fontSize: '14px',
    color: '#374151',
    margin: '0 0 12px 0',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
  },
  platforms: {
    fontSize: '13px',
    color: '#6b7280',
    marginTop: '12px',
    paddingTop: '12px',
    borderTop: '1px solid #e5e7eb',
  },
  riskBox: {
    border: '3px solid',
    borderRadius: '12px',
    padding: '20px',
    background: '#fafafa',
    marginBottom: '20px',
  },
  riskDescription: {
    fontSize: '14px',
    color: '#374151',
    margin: '12px 0 0 0',
    lineHeight: 1.6,
  },
  clustersTable: {
    marginTop: '16px',
  },
  clusterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '8px 0',
    borderBottom: '1px solid #e5e7eb',
  },
  clusterName: {
    width: '140px',
    fontSize: '13px',
    color: '#4b5563',
  },
  clusterBarContainer: {
    flex: 1,
    height: '20px',
    background: '#e5e7eb',
    borderRadius: '10px',
    overflow: 'hidden',
  },
  clusterBar: {
    height: '100%',
    borderRadius: '10px',
    transition: 'width 0.3s',
  },
  clusterLevel: {
    width: '100px',
    fontSize: '12px',
    fontWeight: 'bold',
    textAlign: 'right',
  },
  topClusterBox: {
    background: '#fef3c7',
    border: '2px solid #f59e0b',
    borderRadius: '8px',
    padding: '12px 16px',
    marginTop: '16px',
    fontSize: '14px',
    color: '#92400e',
  },
  recommendationsList: {
    margin: 0,
    paddingLeft: '20px',
  },
  recommendationItem: {
    fontSize: '13px',
    color: '#374151',
    margin: '8px 0',
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
  },
  recommendationNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '24px',
    background: '#667eea',
    color: 'white',
    borderRadius: '50%',
    fontSize: '12px',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  evidenceCount: {
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '12px',
  },
  evidenceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  evidenceItem: {
    display: 'flex',
    gap: '16px',
    background: '#f9fafb',
    borderRadius: '8px',
    padding: '16px',
    borderLeft: '4px solid #10b981',
  },
  evidenceNumber: {
    width: '32px',
    height: '32px',
    background: '#10b981',
    color: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '14px',
    flexShrink: 0,
  },
  evidenceDetails: {
    flex: 1,
  },
  notesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  noteItem: {
    background: '#f3f4f6',
    borderRadius: '8px',
    padding: '16px',
  },
  noteHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  noteDate: {
    fontSize: '12px',
    color: '#6b7280',
  },
  noteText: {
    fontSize: '14px',
    color: '#374151',
    margin: 0,
  },
  auditTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '12px',
  },
  auditTh: {
    background: '#f3f4f6',
    padding: '10px',
    textAlign: 'left',
    borderBottom: '2px solid #e5e7eb',
    fontWeight: 600,
    color: '#374151',
  },
  auditTd: {
    padding: '8px 10px',
    borderBottom: '1px solid #e5e7eb',
    color: '#4b5563',
  },
  footer: {
    marginTop: '40px',
    paddingTop: '20px',
    borderTop: '2px solid #e5e7eb',
    textAlign: 'center',
  },
  footerText: {
    fontSize: '11px',
    color: '#6b7280',
    margin: '0 0 8px 0',
  },
  footerNote: {
    fontSize: '10px',
    color: '#9ca3af',
    margin: 0,
  },
};
